Modify build script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -27,6 +27,11 @@ function test {
         exit 2
     fi
     
+    if [[ -z $(which bats) ]]; then
+        echo "Missing bats, which is required for testing."
+        exit 2
+    fi
+
     bats test/
 }
 
@@ -58,6 +63,7 @@ function push {
 #
 
 actions=("$@")
+
 if [ ${#actions[@]} -eq 0 ]; then
     actions=(build test push)
 fi
